name: CI Workflow

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: ['*']

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: echo "Build step goes here"
    - name: Print some variables
      run: |
        echo "Repository: ${{ github.repository }}"
        echo "Commit SHA: ${{ github.sha }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "Triggered by: ${{ github.event_name }}"
        echo "Triggered by: ${{ github.event_path }}"
    - name: Make script executable
      run: chmod +x ./result.sh
    - name: Run a script
      id: script
      run: |
        # Imagine this script outputs a value we want to capture
        ./result.sh
        result=$(./result.sh)
        echo "RESULT=$result" >> $GITHUB_ENV
    - name: Test
      run: |
        curl -L \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: Bearer ${{ github.token }}" \
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
        -d '{"state":"success","target_url":"https://example.com/build/status","description":"The build succeeded!","context":"continuous-integration/jenkins"}'
